# Trigger
language: ruby
env:
  COMPOSE_VERSION: 1.3.1
rvm:
  - 2.2.0
  - 2.1.5
  - 2.1.0
  - 1.9.3
addons:
  postgresql: '9.3'
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - createdb pliny-gem-test
cache: bundler
notifications:
  hipchat:
    rooms:
      - 5bc7785d2feb4f25901124279daede@API
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
  email: false
script: bundle exec rake
sudo: required
services:
    - docker
